---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: foo
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
       - name: docker-cred
      containers:
        - name: nginx
          image: rameshm1/onc:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
