---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: second-app-bar
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL:  https://github.com/rameshkpit1/argocd-practice.git
    targetRevision: HEAD
    path: env/staging/second-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
=======
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: second-bar
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rameshkpit1/argocd-practice.git
    targetRevision: HEAD
    path: env/staging/second-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
